--- #YAML:1.0
name:               Test-Mock-Simple
version:            0.01
abstract:           A simple way to mock out parts of or a whole module.
author:
    - Erik Tank <tank@jundy.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
